from vivarium_gates_lsff.constants import data_keys


class TransitionString(str):

    def __new__(cls, value):
        # noinspection PyArgumentList
        obj = str.__new__(cls, value.lower())
        obj.from_state, obj.to_state = value.split('_TO_')
        return obj


###########################
# Disease Model variables #
###########################

# TODO input details of model states and transitions
DIARRHEA_MODEL_NAME = data_keys.DIARRHEA.name
SUSCEPTIBLE_STATE_NAME = f'susceptible_to_{DIARRHEA_MODEL_NAME}'
DIARRHEA_WITH_CONDITION_STATE_NAME = DIARRHEA_MODEL_NAME
DIARRHEA_MODEL_STATES = (SUSCEPTIBLE_STATE_NAME, DIARRHEA_WITH_CONDITION_STATE_NAME)
DIARRHEA_MODEL_TRANSITIONS = (
    TransitionString(f'{SUSCEPTIBLE_STATE_NAME}_TO_{DIARRHEA_WITH_CONDITION_STATE_NAME}'),
    TransitionString(f'{DIARRHEA_WITH_CONDITION_STATE_NAME}_TO_{SUSCEPTIBLE_STATE_NAME}'),
)


MEASLES_MODEL_NAME = data_keys.MEASLES.name
MEASLES_SUSCEPTIBLE_STATE_NAME = f'susceptible_to_{MEASLES_MODEL_NAME}'
MEASLES_WITH_CONDITION_STATE_NAME = MEASLES_MODEL_NAME
MEASLES_MODEL_STATES = (MEASLES_SUSCEPTIBLE_STATE_NAME, MEASLES_WITH_CONDITION_STATE_NAME)
MEASLES_MODEL_TRANSITIONS = (
    TransitionString(f'{MEASLES_SUSCEPTIBLE_STATE_NAME}_TO_{MEASLES_WITH_CONDITION_STATE_NAME}'),
    TransitionString(f'{MEASLES_WITH_CONDITION_STATE_NAME}_TO_{MEASLES_SUSCEPTIBLE_STATE_NAME}'),
)


VITAMIN_A_MODEL_NAME = 'vitamin_a_deficiency'
VITAMIN_A_WITH_CONDITION_STATE_NAME = VITAMIN_A_MODEL_NAME
VITAMIN_A_SUSCEPTIBLE_STATE_NAME = f'susceptible_to_{VITAMIN_A_MODEL_NAME}'
VITAMIN_A_MODEL_STATES = (VITAMIN_A_SUSCEPTIBLE_STATE_NAME, VITAMIN_A_WITH_CONDITION_STATE_NAME)
VITAMIN_A_MODEL_TRANSITIONS = (
    TransitionString(f'{VITAMIN_A_SUSCEPTIBLE_STATE_NAME}_TO_{VITAMIN_A_WITH_CONDITION_STATE_NAME}'),
    TransitionString(f'{VITAMIN_A_WITH_CONDITION_STATE_NAME}_TO_{VITAMIN_A_SUSCEPTIBLE_STATE_NAME}')
)

VITAMIN_A_DEFICIENT_EVENT_COUNT = f'{VITAMIN_A_MODEL_NAME}_event_count'
VITAMIN_A_DEFICIENT_EVENT_TIME = f'{VITAMIN_A_MODEL_NAME}_event_time'
VITAMIN_A_ADEQUATE_EVENT_COUNT = f'{VITAMIN_A_SUSCEPTIBLE_STATE_NAME}_event_count'
VITAMIN_A_ADEQUATE_EVENT_TIME = f'{VITAMIN_A_SUSCEPTIBLE_STATE_NAME}_event_time'
VITAMIN_A_PROPENSITY = f'{VITAMIN_A_MODEL_NAME}_propensity'
VITAMIN_A_RISK_CATEGORIES = ['cat1', 'cat2']


STATE_MACHINE_MAP = {
    DIARRHEA_MODEL_NAME: {
        'states': DIARRHEA_MODEL_STATES,
        'transitions': DIARRHEA_MODEL_TRANSITIONS,
    },
    MEASLES_MODEL_NAME: {
        'states': MEASLES_MODEL_STATES,
        'transitions': MEASLES_MODEL_TRANSITIONS,
    },
    VITAMIN_A_MODEL_NAME: {
        'states': VITAMIN_A_MODEL_STATES,
        'transitions': VITAMIN_A_MODEL_TRANSITIONS,
    },
}


STATES = tuple(state for model in STATE_MACHINE_MAP.values() for state in model['states'])
TRANSITIONS = tuple(state for model in STATE_MACHINE_MAP.values() for state in model['transitions'])

