from vivarium_public_health.metrics.utilities import TransitionString

from vivarium_gates_lsff.constants import data_keys


###########################
# Disease Model variables #
###########################

# TODO input details of model states and transitions
DIARRHEA_MODEL_NAME = data_keys.DIARRHEA.name
SUSCEPTIBLE_STATE_NAME = f'susceptible_to_{DIARRHEA_MODEL_NAME}'
DIARRHEA_WITH_CONDITION_STATE_NAME = DIARRHEA_MODEL_NAME
DIARRHEA_MODEL_STATES = (SUSCEPTIBLE_STATE_NAME, DIARRHEA_WITH_CONDITION_STATE_NAME)
DIARRHEA_MODEL_TRANSITIONS = (
    TransitionString(f'{SUSCEPTIBLE_STATE_NAME}_TO_{DIARRHEA_WITH_CONDITION_STATE_NAME}'),
    TransitionString(f'{DIARRHEA_WITH_CONDITION_STATE_NAME}_TO_{SUSCEPTIBLE_STATE_NAME}'),
)


MEASLES_MODEL_NAME = data_keys.MEASLES.name
MEASLES_SUSCEPTIBLE_STATE_NAME = f'susceptible_to_{MEASLES_MODEL_NAME}'
MEASLES_WITH_CONDITION_STATE_NAME = MEASLES_MODEL_NAME
MEASLES_RECOVERED_STATE_NAME = f'recovered_from_{MEASLES_MODEL_NAME}'
MEASLES_MODEL_STATES = (MEASLES_SUSCEPTIBLE_STATE_NAME, MEASLES_WITH_CONDITION_STATE_NAME)
MEASLES_MODEL_TRANSITIONS = (
    TransitionString(f'{MEASLES_SUSCEPTIBLE_STATE_NAME}_TO_{MEASLES_WITH_CONDITION_STATE_NAME}'),
    TransitionString(f'{MEASLES_WITH_CONDITION_STATE_NAME}_TO_{MEASLES_RECOVERED_STATE_NAME}'),
)


VITAMIN_A_MODEL_NAME = 'vitamin_a_deficiency'
VITAMIN_A_WITH_CONDITION_STATE_NAME = VITAMIN_A_MODEL_NAME
VITAMIN_A_SUSCEPTIBLE_STATE_NAME = f'susceptible_to_{VITAMIN_A_MODEL_NAME}'
VITAMIN_A_MODEL_STATES = (VITAMIN_A_SUSCEPTIBLE_STATE_NAME, VITAMIN_A_WITH_CONDITION_STATE_NAME)
VITAMIN_A_MODEL_TRANSITIONS = (
    TransitionString(f'{VITAMIN_A_SUSCEPTIBLE_STATE_NAME}_TO_{VITAMIN_A_WITH_CONDITION_STATE_NAME}'),
    TransitionString(f'{VITAMIN_A_WITH_CONDITION_STATE_NAME}_TO_{VITAMIN_A_SUSCEPTIBLE_STATE_NAME}')
)

VITAMIN_A_DEFICIENT_EVENT_COUNT = f'{VITAMIN_A_MODEL_NAME}_event_count'
VITAMIN_A_DEFICIENT_EVENT_TIME = f'{VITAMIN_A_MODEL_NAME}_event_time'
VITAMIN_A_ADEQUATE_EVENT_COUNT = f'{VITAMIN_A_SUSCEPTIBLE_STATE_NAME}_event_count'
VITAMIN_A_ADEQUATE_EVENT_TIME = f'{VITAMIN_A_SUSCEPTIBLE_STATE_NAME}_event_time'
VITAMIN_A_PROPENSITY = f'{VITAMIN_A_MODEL_NAME}_propensity'
VITAMIN_A_RISK_CATEGORIES = ['cat1', 'cat2']


IRON_DEFICIENCY_MODEL_NAME = 'iron_deficiency'
ANEMIA_SEVERITY_GROUPS = ['none', 'mild', 'moderate', 'severe']
ANEMIA_OBSERVER = 'anemia_observer'


ZINC_DEFICIENCY_RISK_NAME = 'zinc_deficiency'
ZINC_DEFICIENCY_WITH_CONDITION_STATE_NAME = ZINC_DEFICIENCY_RISK_NAME
ZINC_DEFICIENCY_SUSCEPTIBLE_STATE_NAME = f'susceptible_to_{ZINC_DEFICIENCY_RISK_NAME}'
ZINC_DEFICIENCY_RISK_STATES = (ZINC_DEFICIENCY_SUSCEPTIBLE_STATE_NAME, ZINC_DEFICIENCY_WITH_CONDITION_STATE_NAME)


STATE_MACHINE_MAP = {
    DIARRHEA_MODEL_NAME: {
        'states': DIARRHEA_MODEL_STATES,
        'transitions': DIARRHEA_MODEL_TRANSITIONS,
    },
    MEASLES_MODEL_NAME: {
        'states': MEASLES_MODEL_STATES,
        'transitions': MEASLES_MODEL_TRANSITIONS,
    },
    VITAMIN_A_MODEL_NAME: {
        'states': VITAMIN_A_MODEL_STATES,
        'transitions': VITAMIN_A_MODEL_TRANSITIONS,
    },
    IRON_DEFICIENCY_MODEL_NAME: {
        'states': [f'anemia_{i}' for i in ANEMIA_SEVERITY_GROUPS],
        'transitions': [],
    },
    ZINC_DEFICIENCY_RISK_NAME: {
        'states': ZINC_DEFICIENCY_RISK_STATES,
        'transitions': [],
    },
}


STATES = tuple(state for model in STATE_MACHINE_MAP.values() for state in model['states'])
TRANSITIONS = tuple(state for model in STATE_MACHINE_MAP.values() for state in model['transitions'])

